import 'gamepad_service.dart';

/// Database of hardware-specific mappings for various controllers and modes.
/// Following the SDL2 gamecontrollerdb pattern.
const Map<String, Map<String, GameAction>> kControllerMappings = {
  // 8BitDo Micro - Switch mode (macOS IOKit)
  '8BitDo Micro': {
    'a.circle': GameAction.confirm,
    'b.circle': GameAction.back,
    'x.circle': GameAction.detail,
    'y.circle': GameAction.favorite,
    'l.joystick - yAxis': GameAction.verticalAxis,
    'l.joystick - xAxis': GameAction.horizontalAxis,
  },

  // 8BitDo Micro - D mode (Generic D-Input)
  '8BitDo Micro gamepad': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
  },

  // Xbox Controllers (Windows XInput / Generic Bluetooth)
  'Xbox': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
  },

  // Nintendo Switch Pro Controller - XInput / SDL named button variants
  'Nintendo Switch Pro Controller': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'lefttrigger': GameAction.l2,
    'righttrigger': GameAction.r2,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
    'button_8': GameAction.start,
    'button_9': GameAction.select,
  },

  // Joy-Con (L)
  'Joy-Con (L)': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'lefttrigger': GameAction.l2,
    'leftstick': GameAction.horizontalAxis,
    'button_minus': GameAction.select,
    'button_8': GameAction.select,
  },

  // Joy-Con (R)
  'Joy-Con (R)': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'rightshoulder': GameAction.r1,
    'righttrigger': GameAction.r2,
    'rightstick': GameAction.horizontalAxis,
    'button_plus': GameAction.start,
    'button_9': GameAction.start,
  },

  // DualSense / DualShock
  'DualSense': {
    'cross': GameAction.confirm,
    'circle': GameAction.back,
    'square': GameAction.detail,
    'triangle': GameAction.favorite,
  },

  // DualShock 4 (PS4) - still very widely used
  'DualShock 4': {
    'cross': GameAction.confirm,
    'circle': GameAction.back,
    'square': GameAction.detail,
    'triangle': GameAction.favorite,
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'lefttrigger': GameAction.l2,
    'righttrigger': GameAction.r2,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_options': GameAction.select,
    'button_touchpad': GameAction.start,
  },

  // Logitech F310 (wired, D-Input / X-Input)
  'Logitech F310': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'lefttrigger': GameAction.l2,
    'righttrigger': GameAction.r2,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_6': GameAction.select,
    'button_7': GameAction.start,
    'button_8': GameAction.select,
    'button_9': GameAction.start,
  },

  // Logitech F710 (wireless)
  'Logitech F710': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'lefttrigger': GameAction.l2,
    'righttrigger': GameAction.r2,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_6': GameAction.select,
    'button_7': GameAction.start,
  },

  // Google Stadia Controller (Bluetooth mode)
  'Stadia': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'lefttrigger': GameAction.l2,
    'righttrigger': GameAction.r2,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // 8BitDo Pro 2 (D-Input and X-Input modes)
  '8BitDo Pro 2': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'lefttrigger': GameAction.l2,
    'righttrigger': GameAction.r2,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // 8BitDo Ultimate (2.4G and Bluetooth modes)
  '8BitDo Ultimate': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'lefttrigger': GameAction.l2,
    'righttrigger': GameAction.r2,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // PowerA Controllers (generic entry)
  'PowerA': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'lefttrigger': GameAction.l2,
    'righttrigger': GameAction.r2,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // Steam Controller (Valve)
  'Steam Controller': {
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'lefttrigger': GameAction.l2,
    'righttrigger': GameAction.r2,
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // macOS Pro Controller / Switch-style Descriptive Strings
  'Pro Controller': {
    'a.circle': GameAction.confirm,
    'b.circle': GameAction.back,
    'x.circle': GameAction.detail,
    'y.circle': GameAction.favorite,
    'l.joystick - xAxis': GameAction.horizontalAxis,
    'l.joystick - yAxis': GameAction.verticalAxis,
    'dpad - xAxis': GameAction.horizontalAxis,
    'dpad - yAxis': GameAction.verticalAxis,
    'buttonMenu': GameAction.start,
    'buttonOptions': GameAction.select,
    'l.rectangle.roundedbottom': GameAction.l1,
    'r.rectangle.roundedbottom': GameAction.r1,
    'zl.rectangle.roundedtop': GameAction.l2,
    'zr.rectangle.roundedtop': GameAction.r2,
  },

  // Steam Deck
  'Steam Deck': {
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'lefttrigger': GameAction.l2,
    'righttrigger': GameAction.r2,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // GPD Win 4 (built-in handheld controller)
  'GPD Win 4': {
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'lefttrigger': GameAction.l2,
    'righttrigger': GameAction.r2,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
    'button_6': GameAction.start,
    'button_7': GameAction.select,
  },

  // Generic Controller
  'Generic Controller': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'lefttrigger': GameAction.l2,
    'righttrigger': GameAction.r2,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
  },
};

/// Fallback for unknown controllers - covers most XInput-style layouts
const Map<String, GameAction> kDefaultMapping = {
  'button_0': GameAction.confirm,
  'button_1': GameAction.back,
  'button_2': GameAction.detail,
  'button_3': GameAction.favorite,
  'a': GameAction.confirm,
  'b': GameAction.back,
  'x': GameAction.detail,
  'y': GameAction.favorite,

  // Mac/Switch Fallbacks
  'a.circle': GameAction.confirm,
  'b.circle': GameAction.back,
  'x.circle': GameAction.detail,
  'y.circle': GameAction.favorite,
  'cross': GameAction.confirm,
  'circle': GameAction.back,
  'square': GameAction.detail,
  'triangle': GameAction.favorite,
  'l.joystick - xAxis': GameAction.horizontalAxis,
  'l.joystick - yAxis': GameAction.verticalAxis,
  'dpad - xAxis': GameAction.horizontalAxis,
  'dpad - yAxis': GameAction.verticalAxis,
  'buttonMenu': GameAction.start,
  'buttonOptions': GameAction.select,
  'l.rectangle.roundedbottom': GameAction.l1,
  'r.rectangle.roundedbottom': GameAction.r1,
  'zl.rectangle.roundedtop': GameAction.l2,
  'zr.rectangle.roundedtop': GameAction.r2,

  // D-Pad
  'dpad_up': GameAction.up,
  'dpad_down': GameAction.down,
  'dpad_left': GameAction.left,
  'dpad_right': GameAction.right,
  'button_11': GameAction.up,
  'button_12': GameAction.down,
  'button_13': GameAction.left,
  'button_14': GameAction.right,

  // Shoulders / Triggers
  'leftshoulder': GameAction.l1,
  'rightshoulder': GameAction.r1,
  'lefttrigger': GameAction.l2,
  'righttrigger': GameAction.r2,
  'button_4': GameAction.l1,
  'button_5': GameAction.r1,
  'button_6': GameAction.l2,
  'button_7': GameAction.r2,

  // Start / Select
  'button_menu': GameAction.start,
  'button_options': GameAction.select,
  'button_8': GameAction.select,
  'button_9': GameAction.start,
  'start': GameAction.start,
  'select': GameAction.select,
  'back': GameAction.select,
  'guide': GameAction.start,

  // Analog Sticks (axis)
  'leftstick': GameAction.horizontalAxis,
  'rightstick': GameAction.verticalAxis,
  'l.joystick': GameAction.horizontalAxis,
  'r.joystick': GameAction.verticalAxis,
};
