const List<Map<String, dynamic>> kEmulatorDefinitions = [
  {
    'id': 'retroarch',
    'name': 'RetroArch',
    'type': 'direct',
    'windows_url': 'https://buildbot.libretro.com/stable/1.19.1/windows/x86_64/RetroArch.7z',
    'windows_executable': 'RetroArch.exe',
    'linux_executable': 'retroarch',
    'platform_slugs': [
      'gba', 'gbc', 'gb', 'nes', 'snes', 'n64', 'nds', 'psx', 'ps1', 'playstation',
      'psp', 'dc', 'dreamcast', 'segacd', 'saturn', 'megadrive', 'genesis', 'md',
      'gamegear', 'atari2600', 'atari7800', 'lynx', 'neogeo', 'arcade', 'mame',
      'pcengine', 'wonderswan', 'virtualboy', 'msx', 'dos'
    ],
  },
  {
    'id': 'dolphin',
    'name': 'Dolphin',
    'type': 'direct',
    'windows_url': 'https://dl.dolphin-emu.org/builds/dolphin-master-latest-x64.7z',
    'windows_executable': 'Dolphin.exe',
    'linux_executable': 'dolphin-emu',
    'platform_slugs': ['gc', 'gamecube', 'wii', 'ngc'],
  },
  {
    'id': 'eden',
    'name': 'Eden (Switch)',
    'type': 'direct',
    'windows_url': 'https://git.eden-emu.dev/eden-emu/eden/-/releases/permalink/latest/downloads/eden-windows-msvc-install.zip',
    'windows_executable': 'eden.exe',
    'linux_executable': 'eden',
    'platform_slugs': ['switch', 'nintendo-switch', 'ns'],
  },
  {
    'id': 'rpcs3',
    'name': 'RPCS3 (PlayStation 3)',
    'type': 'github',
    'github_repo': 'RPCS3/rpcs3',
    'github_asset_required': ['win64'],
    'github_asset_excluded': ['debug'],
    'windows_executable': 'rpcs3.exe',
    'linux_executable': 'rpcs3',
    'platform_slugs': ['ps3', 'playstation-3', 'playstation3'],
  },
  {
    'id': 'pcsx2',
    'name': 'PCSX2 (PlayStation 2)',
    'type': 'github',
    'github_repo': 'PCSX2/pcsx2',
    'github_asset_required': ['windows', 'Qt'],
    'github_asset_excluded': ['debug', 'sse4', 'arm64'],
    'windows_executable': 'pcsx2-qt.exe',
    'linux_executable': 'pcsx2-qt',
    'platform_slugs': ['ps2', 'playstation-2', 'playstation2'],
  },
  {
    'id': 'azahar',
    'name': 'Azahar (Nintendo 3DS)',
    'type': 'github',
    'github_repo': 'azahar-emu/azahar',
    'github_asset_required': ['windows', 'msys2'],
    'github_asset_excluded': ['debug', 'appimage'],
    'windows_executable': 'azahar.exe',
    'linux_executable': 'azahar',
    'platform_slugs': ['3ds', 'n3ds', 'nintendo-3ds', 'nintendo3ds', 'new-nintendo-3ds', 'new-nintendo-3ds-xl'],
  },
  {
    'id': 'cemu',
    'name': 'Cemu (Wii U)',
    'type': 'github',
    'github_repo': 'cemu-project/Cemu',
    'github_asset_required': ['windows'],
    'github_asset_excluded': ['experimental', 'debug'],
    'windows_executable': 'Cemu.exe',
    'linux_executable': 'cemu',
    'platform_slugs': ['wiiu', 'wii-u', 'nintendo-wii-u', 'nintendo-wiiu'],
  },
  {
    'id': 'xemu',
    'name': 'Xemu (Xbox)',
    'type': 'github',
    'github_repo': 'xemu-project/xemu',
    'github_asset_required': ['win', 'x86_64', 'release'],
    'github_asset_excluded': ['dbg', 'pdb', 'arm', 'macos', 'appimage', 'tar'],
    'windows_executable': 'xemu.exe',
    'linux_executable': 'xemu',
    'platform_slugs': ['xbox'],
  },
  {
    'id': 'xenia_canary',
    'name': 'Xenia Canary (Xbox 360)',
    'type': 'github',
    'github_repo': 'xenia-canary/xenia-canary',
    'github_asset_required': ['windows'],
    'github_asset_excluded': ['debugoptimized', 'debug', 'pdb'],
    'windows_executable': 'xenia_canary.exe',
    'linux_executable': 'xenia_canary',
    'platform_slugs': ['xbox360', 'xbla'],
  },
  {
    'id': 'duckstation',
    'name': 'DuckStation (PlayStation 1)',
    'type': 'github',
    'github_repo': 'stenzek/duckstation',
    'github_asset_required': ['windows', 'x64'],
    'github_asset_excluded': ['nogui', 'debug', 'arm64'],
    'windows_executable': 'duckstation-qt-x64-ReleaseLTCG.exe',
    'linux_executable': 'duckstation-qt',
    'platform_slugs': ['ps1', 'playstation', 'psx'],
  },
];