const List<Map<String, dynamic>> kEmulatorDefinitions = [
  {
    'id': 'retroarch',
    'name': 'RetroArch',
    'type': 'direct',
    'windows_url': 'https://buildbot.libretro.com/stable/1.20.0/windows/x86_64/RetroArch.7z',
    'windows_executable': 'RetroArch.exe',
    'linux_url': 'https://buildbot.libretro.com/stable/1.22.2/linux/x86_64/RetroArch.7z',
    'linux_executable': 'retroarch',
    'macos_url': 'https://buildbot.libretro.com/stable/1.22.2/apple/osx/universal/RetroArch_Metal.dmg',
    'macos_executable': 'RetroArch.app/Contents/MacOS/RetroArch',
    'platform_slugs': [
      'gba', 'gbc', 'gb', 'nes', 'snes', 'n64', 'nds', 'psx', 'ps1', 'playstation',
      'psp', 'dc', 'dreamcast', 'segacd', 'saturn', 'megadrive', 'genesis', 'md',
      'gamegear', 'atari2600', 'atari7800', 'lynx', 'neogeo', 'arcade', 'mame',
      'pcengine', 'wonderswan', 'virtualboy', 'msx', 'dos', '3ds', 'n3ds', 'nintendo-3ds', 'nintendo3ds', 'new-nintendo-3ds', 'new-nintendo-3ds-xl'
    ],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'dolphin',
    'name': 'Dolphin',
    'type': 'dolphin',
    'asset_required_windows': ['x64', '.7z'],
    'asset_required_macos': ['universal', '.dmg'],
    'asset_required_linux': ['x86_64', '.flatpak'],
    'windows_executable': 'Dolphin.exe',
    'linux_executable': 'Dolphin.AppImage',
    'macos_executable': 'Dolphin.app/Contents/MacOS/Dolphin',
    'platform_slugs': ['gc', 'gamecube', 'wii', 'ngc'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'eden',
    'name': 'Eden (Switch)',
    'type': 'gitea',
    'gitea_host': 'git.eden-emu.dev',
    'gitea_repo': 'eden-ci/nightly',
    'windows_executable': 'eden.exe',
    'linux_executable': 'eden',
    'macos_executable': 'Eden.app/Contents/MacOS/Eden',
    'platform_slugs': ['switch', 'nintendo-switch', 'ns'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'ryujinx',
    'name': 'Ryujinx (Switch)',
    'type': 'gitea',
    'gitea_host': 'git.ryujinx.app',
    'gitea_repo': 'Ryubing/Canary',
    'gitea_asset_required_windows': ['win_x64'],
    'gitea_asset_required_macos': ['macos_universal'],
    'gitea_asset_required_linux': ['linux_x64'],
    'windows_executable': 'Ryujinx.exe',
    'linux_executable': 'Ryujinx.AppImage',
    'macos_executable': 'Ryujinx.app/Contents/MacOS/Ryujinx',
    'platform_slugs': ['switch', 'nintendo-switch', 'ns'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'rpcs3',
    'name': 'RPCS3 (PlayStation 3)',
    'type': 'github_multi',
    'github_repos': {
      'windows': 'RPCS3/rpcs3-binaries-win',
      'macos': 'RPCS3/rpcs3-binaries-mac',
      'linux': 'RPCS3/rpcs3-binaries-linux',
    },
    'github_asset_required_windows': ['.7z'],
    'github_asset_required_macos': ['.7z'],
    'github_asset_required_linux': ['.AppImage'],
    'github_asset_excluded': ['debug'],
    'windows_executable': 'rpcs3.exe',
    'linux_executable': 'rpcs3.AppImage',
    'macos_executable': 'rpcs3.app/Contents/MacOS/rpcs3',
    'platform_slugs': ['ps3', 'playstation-3', 'playstation3'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'pcsx2',
    'name': 'PCSX2 (PlayStation 2)',
    'type': 'github',
    'github_repo': 'PCSX2/pcsx2',
    'github_asset_required': ['windows', 'Qt'],
    'github_asset_required_macos': ['macos', 'Qt'],
    'github_asset_required_linux': ['linux', '.appimage'],
    'github_asset_excluded': ['debug', 'sse4'],
    'github_asset_excluded_windows': ['arm64'],
    'windows_executable': 'pcsx2-qt.exe',
    'linux_executable': 'pcsx2-qt.AppImage',
    'macos_executable': 'PCSX2.app/Contents/MacOS/PCSX2',
    'platform_slugs': ['ps2', 'playstation-2', 'playstation2'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'azahar',
    'name': 'Azahar (Nintendo 3DS)',
    'type': 'github',
    'github_repo': 'azahar-emu/azahar',
    'windows_executable': 'azahar.exe',
    'linux_executable': 'azahar.AppImage',
    'macos_executable': 'Azahar.app/Contents/MacOS/Azahar',
    'platform_slugs': ['3ds', 'n3ds', 'nintendo-3ds', 'nintendo3ds', 'new-nintendo-3ds', 'new-nintendo-3ds-xl'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'cemu',
    'name': 'Cemu (Wii U)',
    'type': 'github',
    'github_repo': 'cemu-project/Cemu',
    'github_asset_required': ['windows', 'x64', '.zip'],
    'github_asset_required_macos': ['macos', '.dmg'],
    'github_asset_required_linux': ['x86_64', '.AppImage'],
    'github_asset_excluded': ['debug', 'symbols'],
    'github_asset_excluded_windows': ['linux', 'macos'],
    'github_asset_excluded_macos': ['windows', 'linux'],
    'windows_executable': 'Cemu.exe',
    'linux_executable': 'Cemu.AppImage',
    'macos_executable': 'Cemu.app/Contents/MacOS/Cemu',
    'platform_slugs': ['wiiu', 'wii-u', 'nintendo-wii-u', 'nintendo-wiiu'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'xemu',
    'name': 'Xemu (Xbox)',
    'type': 'github',
    'github_repo': 'xemu-project/xemu',
    'github_asset_required': ['win', 'x86_64', 'release'],
    'github_asset_required_macos': ['macos', 'universal', '.zip'],
    'github_asset_required_linux': ['x86_64', '.AppImage'],
    'github_asset_excluded': ['dbg', 'pdb', 'arm', 'tar'],
    'github_asset_excluded_windows': ['macos'],
    'github_asset_excluded_macos': ['win'],
    'windows_executable': 'xemu.exe',
    'linux_executable': 'xemu.AppImage',
    'macos_executable': 'Xemu.app/Contents/MacOS/xemu',
    'platform_slugs': ['xbox'],
    'supported_platforms': ['windows', 'macos', 'linux'],
  },
  {
    'id': 'xenia_canary',
    'name': 'Xenia Canary (Xbox 360)',
    'type': 'github',
    'github_repo': 'xenia-canary/xenia-canary',
    'github_asset_required': ['windows'],
    'github_asset_excluded': ['debugoptimized', 'debug', 'pdb'],
    'windows_executable': 'xenia_canary.exe',
    'linux_executable': 'xenia_canary.exe', // Linux users use via Wine/Proton
    'platform_slugs': ['xbox360', 'xbla'],
    'supported_platforms': ['windows', 'linux'],
  },
  {
    'id': 'duckstation',
    'name': 'DuckStation (PlayStation 1)',
    'type': 'github',
    'github_repo': 'stenzek/duckstation',
    'github_asset_required': ['windows', 'x64'],
    'github_asset_required_macos': ['mac', 'release'],
    'github_asset_required_linux': ['x64', '.AppImage'],
    'github_asset_excluded': ['nogui', 'debug', 'arm64'],
    'windows_executable': 'duckstation-qt-x64-ReleaseLTCG.exe',
    'linux_executable': 'DuckStation.AppImage',
    'macos_executable': 'DuckStation.app/Contents/MacOS/DuckStation',
    'platform_slugs': ['ps1', 'playstation', 'psx'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'flycast',
    'name': 'Flycast (Dreamcast)',
    'type': 'github',
    'github_repo': 'flyinghead/flycast',
    'github_asset_required': ['win64', '.zip'],
    'github_asset_required_macos': ['macOS', '.zip'],
    'linux_download_note': 'CI builds only at flyinghead.github.io/flycast-builds',
    'github_asset_excluded': ['debug', 'symbols'],
    'github_asset_excluded_windows': ['linux', 'macos'],
    'github_asset_excluded_macos': ['windows', 'linux'],
    'windows_executable': 'flycast.exe',
    'linux_executable': 'flycast.AppImage',
    'macos_executable': 'Flycast.app/Contents/MacOS/Flycast',
    'platform_slugs': ['dc', 'dreamcast', 'naomi', 'naomi2', 'atomiswave', 'cave', 'hikaru'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'melonds',
    'name': 'melonDS',
    'type': 'github',
    'github_repo': 'melonDS-emu/melonDS',
    'github_asset_required_windows': ['windows', 'x86_64', '.zip'],
    'github_asset_required_linux': ['appimage', 'x86_64', '.zip'],
    'github_asset_required_macos': ['macos', 'universal', '.zip'],
    'github_asset_excluded': ['source', 'debug'],
    'github_asset_excluded_macos': ['libretro'],
    'windows_executable': 'melonDS.exe',
    'linux_executable': 'melonDS',
    'macos_executable': 'melonDS.app/Contents/MacOS/melonDS',
    'platform_slugs': ['nds', 'nintendo-ds', 'ds'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'ppsspp',
    'name': 'PPSSPP (PSP)',
    'type': 'github',
    'github_repo': 'hrydgard/ppsspp',
    'github_asset_required_windows': ['Windows', 'x64', '.zip'],
    'github_asset_required_linux': ['Linux', 'x86_64', '.7z'],
    'github_asset_required_macos': ['macOS', '.zip'],
    'github_asset_excluded': ['debug', 'symbols', 'VR'],
    'windows_executable': 'PPSSPPWindows64.exe',
    'linux_executable': 'PPSSPP',
    'macos_executable': 'PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL',
    'supported_platforms': ['windows', 'linux', 'macos'],
    'platform_slugs': ['psp', 'playstation-portable'],
  },
  {
    'id': 'mgba',
    'name': 'mGBA (GBA)',
    'type': 'github',
    'github_repo': 'mgba-emu/mgba',
    'github_asset_required': ['win64', '.7z'],
    'github_asset_required_macos': ['macos', '.dmg'],
    'github_asset_required_linux': ['linux', 'x86_64', '.tar.xz'],
    'github_asset_excluded': ['debug', 'symbols', 'source'],
    'windows_executable': 'mGBA.exe',
    'linux_executable': 'mgba',
    'macos_executable': 'mGBA.app/Contents/MacOS/mGBA',
    'supported_platforms': ['windows', 'linux', 'macos'],
    'platform_slugs': ['gba', 'gbc', 'gb', 'game-boy-advance', 'game-boy-color', 'game-boy'],
  },
  {
    'id': 'mame',
    'name': 'MAME',
    'type': 'github',
    'github_repo': 'mamedev/mame',
    'github_asset_required': ['mame', '64bit', '.exe'],
    'github_asset_excluded': ['debug', 'symbols', 'sources', 'tools'],
    'extraction_type': 'self_extracting',
    'windows_executable': 'mame.exe',
    'linux_executable': 'mame',
    'macos_executable': 'mame',
    'supported_platforms': ['windows', 'linux', 'macos'],
    'platform_slugs': ['arcade', 'mame'],
  },
  {
    'id': 'windows_native',
    'name': 'Windows (Native)',
    'type': 'none',
    'windows_executable': '',
    'linux_executable': '',
    'platform_slugs': ['windows', 'pc', 'win'],
    'supported_platforms': ['windows'],
  },
];
