const List<Map<String, dynamic>> kEmulatorDefinitions = [
  {
    'id': 'retroarch',
    'name': 'RetroArch',
    'type': 'direct',
    'windows_url': 'https://buildbot.libretro.com/stable/2.0/windows/x86_64/RetroArch_x64.zip',
    'windows_executable': 'RetroArch.exe',
    'linux_url': 'https://buildbot.libretro.com/stable/2.0/linux/x86_64/RetroArch.zip',
    'linux_executable': 'retroarch',
    'macos_url': 'https://buildbot.libretro.com/stable/1.22.2/apple/osx/universal/RetroArch_Metal.dmg',
    'macos_executable': 'RetroArch.app/Contents/MacOS/RetroArch',
    'platform_slugs': [
      'gba', 'gbc', 'gb', 'nes', 'snes', 'n64', 'nds', 'psx', 'ps1', 'playstation',
      'psp', 'dc', 'dreamcast', 'segacd', 'saturn', 'megadrive', 'genesis', 'md',
      'gamegear', 'atari2600', 'atari7800', 'lynx', 'neogeo', 'arcade', 'mame',
      'pcengine', 'wonderswan', 'virtualboy', 'msx', 'dos', '3ds', 'n3ds', 'nintendo-3ds', 'nintendo3ds', 'new-nintendo-3ds', 'new-nintendo-3ds-xl'
    ],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'dolphin',
    'name': 'Dolphin',
    'type': 'direct',
    'windows_url': 'https://dl.dolphin-emu.org/builds/dolphin-master-latest-x64.7z',
    'windows_executable': 'Dolphin.exe',
    'linux_executable': 'dolphin-emu',
    'macos_url': 'https://dl.dolphin-emu.org/releases/2603a/dolphin-2603a-universal.dmg',
    'macos_executable': 'Dolphin.app/Contents/MacOS/Dolphin',
    'platform_slugs': ['gc', 'gamecube', 'wii', 'ngc'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'eden',
    'name': 'Eden (Switch)',
    'type': 'direct',
    'windows_url': 'https://git.eden-emu.dev/eden-emu/eden/-/releases/permalink/latest/downloads/eden-windows-msvc-install.zip',
    'windows_executable': 'eden.exe',
    'linux_executable': 'eden',
    'macos_url': 'https://git.eden-emu.dev/eden-emu/eden/releases/download/v0.2.0-rc2/Eden-macOS-v0.2.0-rc2.tar.gz',
    'macos_executable': 'Eden.app/Contents/MacOS/Eden',
    'platform_slugs': ['switch', 'nintendo-switch', 'ns'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'rpcs3',
    'name': 'RPCS3 (PlayStation 3)',
    'type': 'github',
    'github_repo': 'RPCS3/rpcs3',
    'github_repo_macos': 'RPCS3/rpcs3-binaries-mac-arm64',
    'github_asset_required': ['win64'],
    'github_asset_required_macos': ['macos', 'aarch64', '.7z'],
    'github_asset_excluded': ['debug'],
    'windows_executable': 'rpcs3.exe',
    'linux_executable': 'rpcs3',
    'macos_executable': 'RPCS3.app/Contents/MacOS/RPCS3',
    'platform_slugs': ['ps3', 'playstation-3', 'playstation3'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'pcsx2',
    'name': 'PCSX2 (PlayStation 2)',
    'type': 'github',
    'github_repo': 'PCSX2/pcsx2',
    'github_asset_required': ['windows', 'Qt'],
    'github_asset_required_macos': ['macos', 'Qt'],
    'github_asset_excluded': ['debug', 'sse4'],
    'github_asset_excluded_windows': ['arm64'],
    'windows_executable': 'pcsx2-qt.exe',
    'linux_executable': 'pcsx2-qt',
    'macos_executable': 'PCSX2.app/Contents/MacOS/PCSX2',
    'platform_slugs': ['ps2', 'playstation-2', 'playstation2'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'azahar',
    'name': 'Azahar (Nintendo 3DS)',
    'type': 'github',
    'github_repo': 'azahar-emu/azahar',
    'github_asset_required_windows': ['windows', 'msys2'],
    'github_asset_required_macos': ['macos', 'arm64'],
    'github_asset_excluded_windows': ['debug', 'appimage'],
    'github_asset_excluded_macos': ['debug', 'libretro'],
    'windows_executable': 'azahar.exe',
    'linux_executable': 'azahar',
    'macos_executable': 'Azahar.app/Contents/MacOS/azahar',
    'platform_slugs': ['3ds', 'n3ds', 'nintendo-3ds', 'nintendo3ds', 'new-nintendo-3ds', 'new-nintendo-3ds-xl'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'cemu',
    'name': 'Cemu (Wii U)',
    'type': 'github',
    'github_repo': 'cemu-project/Cemu',
    'github_asset_required': ['windows', 'x64', '.zip'],
    'github_asset_excluded': ['debug', 'symbols', 'linux', 'macos'],
    'windows_executable': 'Cemu.exe',
    'linux_executable': 'cemu',
    'platform_slugs': ['wiiu', 'wii-u', 'nintendo-wii-u', 'nintendo-wiiu'],
    'supported_platforms': ['windows', 'linux'],
  },
  {
    'id': 'xemu',
    'name': 'Xemu (Xbox)',
    'type': 'github',
    'github_repo': 'xemu-project/xemu',
    'github_asset_required': ['win', 'x86_64', 'release'],
    'github_asset_excluded': ['dbg', 'pdb', 'arm', 'macos', 'appimage', 'tar'],
    'windows_executable': 'xemu.exe',
    'linux_executable': 'xemu',
    'platform_slugs': ['xbox'],
    'supported_platforms': ['windows'],
  },
  {
    'id': 'xenia_canary',
    'name': 'Xenia Canary (Xbox 360)',
    'type': 'github',
    'github_repo': 'xenia-canary/xenia-canary',
    'github_asset_required': ['windows'],
    'github_asset_excluded': ['debugoptimized', 'debug', 'pdb'],
    'windows_executable': 'xenia_canary.exe',
    'linux_executable': 'xenia_canary',
    'platform_slugs': ['xbox360', 'xbla'],
    'supported_platforms': ['windows'],
  },
  {
    'id': 'duckstation',
    'name': 'DuckStation (PlayStation 1)',
    'type': 'github',
    'github_repo': 'stenzek/duckstation',
    'github_asset_required': ['windows', 'x64'],
    'github_asset_required_macos': ['mac', 'Qt'],
    'github_asset_excluded': ['nogui', 'debug', 'arm64'],
    'windows_executable': 'duckstation-qt-x64-ReleaseLTCG.exe',
    'linux_executable': 'duckstation-qt',
    'macos_executable': 'DuckStation.app/Contents/MacOS/DuckStation',
    'platform_slugs': ['ps1', 'playstation', 'psx'],
    'supported_platforms': ['windows', 'linux', 'macos'],
  },
  {
    'id': 'flycast',
    'name': 'Flycast (Dreamcast)',
    'type': 'github',
    'github_repo': 'flyinghead/flycast',
    'github_asset_required': ['win64', '.zip'],
    'github_asset_excluded': ['debug', 'symbols', 'linux', 'macos'],
    'windows_executable': 'flycast.exe',
    'linux_executable': 'flycast',
    'platform_slugs': ['dc', 'dreamcast', 'naomi', 'naomi2', 'atomiswave', 'cave', 'hikaru'],
    'supported_platforms': ['windows', 'linux'],
  },
  {
    'id': 'melonds',
    'name': 'melonDS',
    'type': 'github',
    'github_repo': 'melonDS-emu/melonDS',
    'github_asset_required': ['win', '.zip'],
    'github_asset_excluded': ['source', 'debug'],
    'windows_executable': 'melonDS.exe',
    'linux_executable': 'melonDS',
    'platform_slugs': ['nds', 'nintendo-ds', 'ds'],
    'supported_platforms': ['windows', 'linux'],
  },
  {
    'id': 'ppsspp',
    'name': 'PPSSPP (PSP)',
    'type': 'direct',
    'github_repo': 'hrydgard/ppsspp',
    'github_asset_required': ['Windows', 'x64', '.zip'],
    'github_asset_excluded': ['debug', 'symbols', 'VR'],
    'windows_executable': 'PPSSPPWindows64.exe',
    'linux_executable': 'PPSSPP',
    'macos_url': 'https://github.com/hrydgard/ppsspp/releases/download/v1.20.3/PPSSPPSDL-macOS-v1.20.3.zip',
    'macos_executable': 'PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL',
    'supported_platforms': ['windows', 'linux', 'macos'],
    'platform_slugs': ['psp', 'playstation-portable'],
  },
  {
    'id': 'mgba',
    'name': 'mGBA (GBA)',
    'type': 'github',
    'github_repo': 'mgba-emu/mgba',
    'github_asset_required': ['win64', '.7z'],
    'github_asset_excluded': ['debug', 'symbols', 'source'],
    'windows_executable': 'mGBA.exe',
    'linux_executable': 'mgba',
    'supported_platforms': ['windows', 'linux'],
    'platform_slugs': ['gba', 'gbc', 'gb', 'game-boy-advance', 'game-boy-color', 'game-boy'],
  },
  {
    'id': 'mame',
    'name': 'MAME',
    'type': 'github',
    'github_repo': 'mamedev/mame',
    'github_asset_required': ['x64.exe'],
    'github_asset_excluded': ['debug', 'symbols', 'sources', 'tools'],
    'extraction_type': 'self_extracting',
    'windows_executable': 'mame.exe',
    'linux_executable': 'mame',
    'supported_platforms': ['windows', 'linux'],
    'platform_slugs': ['arcade', 'mame'],
  },
  {
    'id': 'windows_native',
    'name': 'Windows (Native)',
    'type': 'none',
    'windows_executable': '',
    'linux_executable': '',
    'platform_slugs': ['windows', 'pc', 'win'],
    'supported_platforms': ['windows'],
  },
];
