// Mocks generated by Mockito 5.4.6 from annotations
// in freegosy/test/unit/paginated_games_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i7;

import 'package:freegosy/core/romm/romm_models.dart' as _i2;
import 'package:freegosy/core/romm/romm_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRomMConfig_0 extends _i1.SmartFake implements _i2.RomMConfig {
  _FakeRomMConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RommService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRommService extends _i1.Mock implements _i3.RommService {
  MockRommService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RomMConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeRomMConfig_0(this, Invocation.getter(#config)),
          )
          as _i2.RomMConfig);

  @override
  String get authHeader =>
      (super.noSuchMethod(
            Invocation.getter(#authHeader),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#authHeader),
            ),
          )
          as String);

  @override
  _i5.Future<void> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Platform>> getPlatforms() =>
      (super.noSuchMethod(
            Invocation.method(#getPlatforms, []),
            returnValue: _i5.Future<List<_i2.Platform>>.value(<_i2.Platform>[]),
          )
          as _i5.Future<List<_i2.Platform>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getCollections() =>
      (super.noSuchMethod(
            Invocation.method(#getCollections, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  String? resolveCoverUrl(_i2.Game? game) =>
      (super.noSuchMethod(Invocation.method(#resolveCoverUrl, [game]))
          as String?);

  @override
  _i5.Future<List<_i2.Game>> getGames(String? platformId) =>
      (super.noSuchMethod(
            Invocation.method(#getGames, [platformId]),
            returnValue: _i5.Future<List<_i2.Game>>.value(<_i2.Game>[]),
          )
          as _i5.Future<List<_i2.Game>>);

  @override
  _i5.Future<List<_i2.Game>> getAllGames({String? platformId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllGames, [], {#platformId: platformId}),
            returnValue: _i5.Future<List<_i2.Game>>.value(<_i2.Game>[]),
          )
          as _i5.Future<List<_i2.Game>>);

  @override
  _i5.Future<List<_i2.Game>> getRecentlyPlayed({int? limit = 15}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyPlayed, [], {#limit: limit}),
            returnValue: _i5.Future<List<_i2.Game>>.value(<_i2.Game>[]),
          )
          as _i5.Future<List<_i2.Game>>);

  @override
  _i5.Future<({List<_i2.Game> games, int total})> getGamesPage({
    int? offset = 0,
    int? limit = 50,
    String? platformId,
    String? search,
    List<String>? genres = const [],
    List<String>? regions = const [],
    List<String>? languages = const [],
    List<String>? collections = const [],
    List<String>? statuses = const [],
    bool? lastPlayed,
    bool? withCharIndex = false,
    bool? withFilterValues = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGamesPage, [], {
              #offset: offset,
              #limit: limit,
              #platformId: platformId,
              #search: search,
              #genres: genres,
              #regions: regions,
              #languages: languages,
              #collections: collections,
              #statuses: statuses,
              #lastPlayed: lastPlayed,
              #withCharIndex: withCharIndex,
              #withFilterValues: withFilterValues,
            }),
            returnValue: _i5.Future<({List<_i2.Game> games, int total})>.value((
              games: <_i2.Game>[],
              total: 0,
            )),
          )
          as _i5.Future<({List<_i2.Game> games, int total})>);

  @override
  _i5.Future<_i2.Game?> getRandomGame() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomGame, []),
            returnValue: _i5.Future<_i2.Game?>.value(),
          )
          as _i5.Future<_i2.Game?>);

  @override
  _i5.Future<List<_i2.SaveFile>> getSaves(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getSaves, [gameId]),
            returnValue: _i5.Future<List<_i2.SaveFile>>.value(<_i2.SaveFile>[]),
          )
          as _i5.Future<List<_i2.SaveFile>>);

  @override
  String getDownloadUrl(_i2.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [game]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getDownloadUrl, [game]),
            ),
          )
          as String);

  @override
  _i5.Future<bool> uploadSave(
    String? gameId,
    _i6.File? saveFile, {
    String? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadSave, [gameId, saveFile], {#slot: slot}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> pruneOldSaves(String? gameId, {int? keepCount = 5}) =>
      (super.noSuchMethod(
            Invocation.method(
              #pruneOldSaves,
              [gameId],
              {#keepCount: keepCount},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getSavesList(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getSavesList, [gameId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>?> getLatestSave(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestSave, [gameId]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<_i7.Uint8List?> downloadSave(String? saveUrl) =>
      (super.noSuchMethod(
            Invocation.method(#downloadSave, [saveUrl]),
            returnValue: _i5.Future<_i7.Uint8List?>.value(),
          )
          as _i5.Future<_i7.Uint8List?>);

  @override
  _i5.Future<List<_i2.Firmware>> getFirmware({String? platformId}) =>
      (super.noSuchMethod(
            Invocation.method(#getFirmware, [], {#platformId: platformId}),
            returnValue: _i5.Future<List<_i2.Firmware>>.value(<_i2.Firmware>[]),
          )
          as _i5.Future<List<_i2.Firmware>>);

  @override
  String getFirmwareDownloadUrl(_i2.Firmware? firmware) =>
      (super.noSuchMethod(
            Invocation.method(#getFirmwareDownloadUrl, [firmware]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getFirmwareDownloadUrl, [firmware]),
            ),
          )
          as String);

  @override
  _i5.Future<_i7.Uint8List?> downloadFirmware(
    _i2.Firmware? firmware, {
    void Function(int, int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFirmware,
              [firmware],
              {#onProgress: onProgress},
            ),
            returnValue: _i5.Future<_i7.Uint8List?>.value(),
          )
          as _i5.Future<_i7.Uint8List?>);

  @override
  _i5.Future<bool> updateRomProps(
    String? romId, {
    bool? backlogged,
    bool? nowPlaying,
    int? rating,
    String? status,
    int? completion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateRomProps,
              [romId],
              {
                #backlogged: backlogged,
                #nowPlaying: nowPlaying,
                #rating: rating,
                #status: status,
                #completion: completion,
              },
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
