// Mocks generated by Mockito 5.4.6 from annotations
// in freegosy/test/unit/strategy_registry_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:freegosy/core/romm/romm_models.dart' as _i5;
import 'package:freegosy/core/storage/directory_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DirectoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDirectoryService extends _i1.Mock implements _i2.DirectoryService {
  MockDirectoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get romsRootPath =>
      (super.noSuchMethod(
            Invocation.getter(#romsRootPath),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#romsRootPath),
            ),
          )
          as String);

  @override
  String get emulatorsRootPath =>
      (super.noSuchMethod(
            Invocation.getter(#emulatorsRootPath),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#emulatorsRootPath),
            ),
          )
          as String);

  @override
  set romsRootPath(String? value) => super.noSuchMethod(
    Invocation.setter(#romsRootPath, value),
    returnValueForMissingStub: null,
  );

  @override
  set emulatorsRootPath(String? value) => super.noSuchMethod(
    Invocation.setter(#emulatorsRootPath, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> loadEmulatorPathOverrides() =>
      (super.noSuchMethod(
            Invocation.method(#loadEmulatorPathOverrides, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setEmulatorPathOverride(String? emulatorId, String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorPathOverride, [emulatorId, path]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String? getEmulatorPathOverride(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorPathOverride, [emulatorId]),
          )
          as String?);

  @override
  _i4.Future<void> setRomsRoot(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setRomsRoot, [path]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setEmulatorsRoot(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorsRoot, [path]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> getRomDirectory(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getRomDirectory, [game]),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(#getRomDirectory, [game]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> getRomFilePath(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getRomFilePath, [game]),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(#getRomFilePath, [game]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String?> findExistingRomPath(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#findExistingRomPath, [game]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> resolveSevenZipPath() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSevenZipPath, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String> getEmulatorDirectory(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorDirectory, [emulatorId]),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(#getEmulatorDirectory, [emulatorId]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> getEmulatorSystemDirectory(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorSystemDirectory, [emulatorId]),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(#getEmulatorSystemDirectory, [emulatorId]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> deleteEmulator(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmulator, [emulatorId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> getEmulatorExecutable(
    String? emulatorId,
    String? executableName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorExecutable, [
              emulatorId,
              executableName,
            ]),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(#getEmulatorExecutable, [
                  emulatorId,
                  executableName,
                ]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String?> findEmulatorExecutable(
    String? emulatorId,
    String? executableName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findEmulatorExecutable, [
              emulatorId,
              executableName,
            ]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> isEmulatorInstalled(
    String? emulatorId,
    String? executableName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isEmulatorInstalled, [
              emulatorId,
              executableName,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isRomDownloaded(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#isRomDownloaded, [game]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> deleteRom(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRom, [game]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
