class GamingQuote {
  final String quote;
  final String game;

  const GamingQuote({required this.quote, required this.game});
}

class GamingQuotes {
  static const List<GamingQuote> quotes = [
    GamingQuote(quote: "Kept you waiting, huh?", game: "Metal Gear Solid"),
    GamingQuote(quote: "It's dangerous to go alone! Take this.", game: "The Legend of Zelda"),
    GamingQuote(quote: "The cake is a lie.", game: "Portal"),
    GamingQuote(quote: "War... war never changes.", game: "Fallout"),
    GamingQuote(quote: "Would you kindly?", game: "BioShock"),
    GamingQuote(quote: "Thank you Mario! But our princess is in another castle!", game: "Super Mario Bros."),
    GamingQuote(quote: "What is a man? A miserable little pile of secrets!", game: "Castlevania: SotN"),
    GamingQuote(quote: "Praise the Sun!", game: "Dark Souls"),
    GamingQuote(quote: "Hey! Listen!", game: "The Legend of Zelda: Ocarina of Time"),
    GamingQuote(quote: "You Died.", game: "Dark Souls"),
    GamingQuote(quote: "Snake? Snake!? SNAAAAAAKE!", game: "Metal Gear Solid"),
    GamingQuote(quote: "Do a barrel roll!", game: "Star Fox 64"),
    GamingQuote(quote: "Rise and shine, Mr. Freeman.", game: "Half-Life 2"),
    GamingQuote(quote: "Nothing is true, everything is permitted.", game: "Assassin's Creed"),
    GamingQuote(quote: "Protocol 3: Protect the Pilot.", game: "Titanfall 2"),
    GamingQuote(quote: "Our destiny is not written for us, but by us.", game: "Halo 4"),
    GamingQuote(quote: "You cannot kill me! I am sub-human!", game: "Devil May Cry V"),
    GamingQuote(quote: "A man chooses, a slave obeys.", game: "BioShock"),
    GamingQuote(quote: "I used to be an adventurer like you, then I took an arrow in the knee.", game: "The Elder Scrolls V: Skyrim"),
    GamingQuote(quote: "Hadouken!", game: "Street Fighter"),
    GamingQuote(quote: "Finish Him!", game: "Mortal Kombat"),
    GamingQuote(quote: "The right man in the wrong place can make all the difference in the world.", game: "Half-Life 2"),
    GamingQuote(quote: "All your base are belong to us.", game: "Zero Wing"),
    GamingQuote(quote: "You standard-model humans are so fragile.", game: "Portal 2"),
    GamingQuote(quote: "It is pitch black. You are likely to be eaten by a grue.", game: "Zork"),
    GamingQuote(quote: "I am Error.", game: "Zelda II: The Adventure of Link"),
    GamingQuote(quote: "Wake me, when you need me.", game: "Halo 3"),
    GamingQuote(quote: "A famous explorer once said that the extraordinary is in what we do, not who we are.", game: "Tomb Raider"),
    GamingQuote(quote: "It's time to kick ass and chew bubble gum... and I'm all out of gum.", game: "Duke Nukem 3D"),
    GamingQuote(quote: "The strength of a soldier comes from the drive in his heart.", game: "Crisis Core: Final Fantasy VII"),
    GamingQuote(quote: "No cost too great. No mind to think. No will to break.", game: "Hollow Knight"),
    GamingQuote(quote: "Despite everything, it's still you.", game: "Undertale"),
    GamingQuote(quote: "In a world without gold, we might've been heroes.", game: "Assassin's Creed IV: Black Flag"),
    GamingQuote(quote: "Stand in the ashes of a trillion dead souls, and ask the ghosts if honor matters.", game: "Mass Effect 3"),
    GamingQuote(quote: "What is better? To be born good or to overcome your evil nature through great effort?", game: "The Elder Scrolls V: Skyrim"),
    GamingQuote(quote: "I survive because the fire inside burns brighter than the fire around me.", game: "Fallout: New Vegas"),
    GamingQuote(quote: "You are filled with determination.", game: "Undertale"),
    GamingQuote(quote: "We work in the dark to serve the light.", game: "Assassin's Creed"),
    GamingQuote(quote: "Every puzzle has an answer.", game: "Professor Layton and the Curious Village"),
    GamingQuote(quote: "Get over here!", game: "Mortal Kombat"),
    GamingQuote(quote: "Science isn't about WHY. It's about WHY NOT!", game: "Portal 2"),
    GamingQuote(quote: "Good men mean well. We just don't always end up doing well.", game: "Dead Space 3"),
    GamingQuote(quote: "Endure and survive.", game: "The Last of Us"),
    GamingQuote(quote: "History is written by the victors.", game: "Call of Duty: Modern Warfare 2"),
    GamingQuote(quote: "If the world chooses to become my enemy, I will fight just as I always have.", game: "Sonic the Hedgehog"),
    GamingQuote(quote: "Even in the darkest times, there is always a way.", game: "Kingdom Hearts"),
    GamingQuote(quote: "Some tree standing in a forest doesn't make a world.", game: "Disco Elysium"),
    GamingQuote(quote: "Don't wish it were easier. Wish you were better.", game: "Animal Crossing"),
    GamingQuote(quote: "May the Triforce be with you.", game: "The Legend of Zelda"),
    GamingQuote(quote: "Booker, are you afraid of God?", game: "BioShock Infinite"),
    GamingQuote(quote: "You've met with a terrible fate, haven't you?", game: "The Legend of Zelda: Majora's Mask"),
    GamingQuote(quote: "You have died of dysentery.", game: "The Oregon Trail"),
    GamingQuote(quote: "I am Andrew Ryan, and I'm here to ask you a question.", game: "BioShock"),
    GamingQuote(quote: "The light of the campfire warm our bones.", game: "Dark Souls"),
    GamingQuote(quote: "The healthy human mind doesn't wake up in the morning thinking this is its last day on Earth.", game: "Call of Duty: Modern Warfare 2"),
    GamingQuote(quote: "We all make choices, but in the end our choices make us.", game: "BioShock"),
    GamingQuote(quote: "I require more Vespene Gas.", game: "StarCraft"),
    GamingQuote(quote: "Construct additional Pylons.", game: "StarCraft"),
    GamingQuote(quote: "Steel wins battles, gold wins wars.", game: "Dota 2"),
    GamingQuote(quote: "The world is a cruel place, and we're all just trying to survive.", game: "Red Dead Redemption"),
    GamingQuote(quote: "If you find yourself in a dark place, remember that you are the light.", game: "Alan Wake"),
    GamingQuote(quote: "Nothing can stop us now.", game: "Grand Theft Auto: San Andreas"),
    GamingQuote(quote: "The path of the righteous man is beset on all sides.", game: "Pulp Fiction / Payday 2"),
    GamingQuote(quote: "May your heart be your guiding key.", game: "Kingdom Hearts"),
    GamingQuote(quote: "There are no heroes here. Only survivors.", game: "Spec Ops: The Line"),
    GamingQuote(quote: "Ah, shit, here we go again.", game: "Grand Theft Auto: San Andreas"),
    GamingQuote(quote: "It's a beautiful day outside. Birds are singing, flowers are blooming...", game: "Undertale"),
    GamingQuote(quote: "Boy!", game: "God of War"),
    GamingQuote(quote: "I'm looking for a man named Spencer.", game: "Resident Evil"),
    GamingQuote(quote: "The master of unlocking.", game: "Resident Evil"),
    GamingQuote(quote: "Stay awhile and listen!", game: "Diablo II"),
    GamingQuote(quote: "You cannot pass!", game: "The Lord of the Rings: The Third Age"),
    GamingQuote(quote: "Press F to pay respects.", game: "Call of Duty: Advanced Warfare"),
    GamingQuote(quote: "It's a me, Mario!", game: "Super Mario 64"),
    GamingQuote(quote: "Waka waka!", game: "Pac-Man"),
    GamingQuote(quote: "No gods or kings. Only man.", game: "BioShock"),
    GamingQuote(quote: "Behind you! A giant three-headed monkey!", game: "The Secret of Monkey Island"),
    GamingQuote(quote: "A scatter of rust and plaster... and then the sea.", game: "Disco Elysium"),
    GamingQuote(quote: "Home is where the hearth is.", game: "Minecraft"),
    GamingQuote(quote: "You are not prepared!", game: "World of Warcraft"),
    GamingQuote(quote: "I never asked for this.", game: "Deus Ex: Human Revolution"),
    GamingQuote(quote: "Prepare for unforeseen consequences.", game: "Half-Life 2"),
    GamingQuote(quote: "Defeat is not the worst of failures. Not to have tried is the true failure.", game: "Darkest Dungeon"),
    GamingQuote(quote: "Remind yourself that overconfidence is a slow and insidious killer.", game: "Darkest Dungeon"),
    GamingQuote(quote: "I am Malenia, Blade of Miquella.", game: "Elden Ring"),
    GamingQuote(quote: "Foul tarnished, in search of the Elden Ring.", game: "Elden Ring"),
    GamingQuote(quote: "Farewell, good hunter. May you find your worth in the waking world.", game: "Bloodborne"),
    GamingQuote(quote: "We are born of the blood, made men by the blood, undone by the blood.", game: "Bloodborne"),
    GamingQuote(quote: "Tonight, Gehrman joins the hunt.", game: "Bloodborne"),
    GamingQuote(quote: "A hunter is a hunter, even in a dream.", game: "Bloodborne"),
    GamingQuote(quote: "True victory is to give all of yourself for what you believe in.", game: "Final Fantasy XIV"),
    GamingQuote(quote: "We must be better than this.", game: "God of War"),
    GamingQuote(quote: "Death can have me, when it earns me.", game: "God of War: Ragnarök"),
    GamingQuote(quote: "To the skies, See! The stars shine for you.", game: "Outer Wilds"),
    GamingQuote(quote: "The universe is, and we are.", game: "Outer Wilds"),
    GamingQuote(quote: "Be excellent to each other.", game: "Bill & Ted's Excellent Video Game Adventure"),
    GamingQuote(quote: "The cosmos, of course!", game: "Bloodborne"),
    GamingQuote(quote: "I have a plan!", game: "Red Dead Redemption 2"),
    GamingQuote(quote: "Outlaws for life.", game: "Red Dead Redemption 2"),
    GamingQuote(quote: "Ain't no such thing as civilized.", game: "Red Dead Redemption 2"),
    GamingQuote(quote: "You're a good man, Arthur Morgan.", game: "Red Dead Redemption 2"),
    GamingQuote(quote: "I'm a survivor, Black Lung. Real survivor.", game: "Red Dead Redemption 2"),
    GamingQuote(quote: "War is when the young and stupid are tricked by the old and bitter.", game: "Grand Theft Auto IV"),
    GamingQuote(quote: "So this is what the dream feels like. This is the victory we longed for.", game: "Grand Theft Auto IV"),
    GamingQuote(quote: "Sometimes it's the journey that teaches you a lot about your destination.", game: "Uncharted: Drake's Fortune"),
    GamingQuote(quote: "Greatness from small beginnings.", game: "Uncharted 3: Drake's Deception"),
    GamingQuote(quote: "Sic Parvis Magna.", game: "Uncharted"),
    GamingQuote(quote: "Don't make a girl a promise... if you know you can't keep it.", game: "Halo 2"),
    GamingQuote(quote: "I am the monument to all your sins.", game: "Halo 2"),
    GamingQuote(quote: "Were it so easy.", game: "Halo 3"),
    GamingQuote(quote: "Spartans never die. They're just missing in action.", game: "Halo: Reach"),
    GamingQuote(quote: "Remember Reach.", game: "Halo: Reach"),
    GamingQuote(quote: "I think we're just getting started.", game: "Halo: Combat Evolved"),
    GamingQuote(quote: "No, Sir. All mind, all heart, all soul.", game: "Titanfall 2"),
    GamingQuote(quote: "Trust me.", game: "Titanfall 2"),
    GamingQuote(quote: "Keep your eyes on the horizon.", game: "Sea of Thieves"),
    GamingQuote(quote: "The light of day is a rare gift.", game: "Metro 2033"),
    GamingQuote(quote: "The wind is howling.", game: "The Witcher 3: Wild Hunt"),
  ];
}
